### ISSUE TITLE
firmwarerevision cannot be empty

### ISSUE THREAD

**Issue by tvillingett** [cflurin/homebridge-mqtt#51]
I'm not sure if it is in homebridge or mqtt this is an error, but it seems like it crashes when the firmwarerevision is empty. This is when I reset the whole configuration and add a bridge and then each accessory (they add automatically in iOS 11, one at a time. It think it is here it asks for the firmwarerevision)
`18:04:20 - [mqtt] identify name 'fönsterbadrum' manufacturer 'homebridge-mqtt' model 'v0.4.5' serialnumber '2017-10-19T05:41' firmwarerevision ''
18:04:20 - TypeError: Cannot read property 'value' of undefined
    at Controller.identify (/usr/local/lib/node_modules/homebridge-mqtt/lib/controller.js:389:132)
    at Accessory.identify (/usr/local/lib/node_modules/homebridge-mqtt/lib/accessory.js:302:3)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge-mqtt/lib/accessory.js:219:61)
    at emitTwo (events.js:87:13)
    at PlatformAccessory.emit (events.js:172:7)
    at PlatformAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:155:12)
    at emitTwo (events.js:87:13)
    at Accessory.emit (events.js:172:7)
    at Accessory._identificationRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:121:10)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:940:14)
    at emitMany (events.js:108:13)
    at Characteristic.emit (events.js:182:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:292:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:812:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:757:8)
    at emitMany (events.js:108:13)
    at HAPServer.emit (events.js:182:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickDomainCallback (node.js:384:17)
18:04:21 - Unhandled Error Detected :  TypeError: Cannot read property 'value' of undefined
    at Controller.identify (/usr/local/lib/node_modules/homebridge-mqtt/lib/controller.js:389:132)
    at Accessory.identify (/usr/local/lib/node_modules/homebridge-mqtt/lib/accessory.js:302:3)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge-mqtt/lib/accessory.js:219:61)
    at emitTwo (events.js:87:13)
    at PlatformAccessory.emit (events.js:172:7)
    at PlatformAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:155:12)
    at emitTwo (events.js:87:13)
    at Accessory.emit (events.js:172:7)
    at Accessory._identificationRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:121:10)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:940:14)
    at emitMany (events.js:108:13)
    at Characteristic.emit (events.js:182:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:292:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:812:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:757:8)
    at emitMany (events.js:108:13)
    at HAPServer.emit (events.js:182:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickDomainCallback (node.js:384:17)
`

**Comment by tvillingett** [comment]
It seems like it was not only for mqtt accessories, so I will try newer homebridge (I was using 0.4.28 and will update to 0.4.33)
